#!/bin/bash

WINEHQ="latest"
ROOT_DIR="/home/thomas/games/dmc3se"
#RUN_EXE="SPEED2.EXE"
WINETRICKS="vd=1280x1024"
#SET_LAA="SPEED2.EXE"
SDL_JOYSTICK_DEVICE="/dev/input/js0"
# invert X,Y for dmc3se
#"jscal -u 6,1,0,2,5,16,17,12,288,289,290,291,292,293,294,295,296,297,298,299 /dev/input/js0"
JSCAL="6,1,0,2,5,16,17,12,288,289,290,291,292,293,294,295,296,297,298,299"

. $(dirname $(realpath $0))/shared/controller/ps2-alt
. $(dirname $(realpath $0))/shared/docker-run
