#!/bin/bash

WINEHQ="latest"
ROOT_DIR="/home/thomas/games/dmc3se"
RUN="wine DMC3SE.EXE"
WINETRICKS=""
SET_LAA=""


. $(dirname $(realpath $0))/shared/controller/triggers
. $(dirname $(realpath $0))/shared/docker-run
