#!/bin/bash

WINEHQ="latest"
ROOT_DIR="/home/thomas/games/dmc3se"
RUN_EXE="DMC3SE.EXE"
WINETRICKS=""
SET_LAA=""
SDL_JOYSTICK_DEVICE="/dev/input/js0"
# invert X,Y
JSCAL="6,1,0,2,5,16,17,12,288,289,290,291,292,293,294,295,296,297,298,299"

. $(dirname $(realpath $0))/shared/docker-run
