#!/bin/bash

WINEHQ="latest"
ROOT_DIR="/home/thomas/games/gtavc"
RUN_EXE="gta-vc.exe"
WINETRICKS="win7 vd=1920x1080"
SDL_JOYSTICK_DEVICE="/dev/input/js0"
JSCAL="6,0,1,2,5,16,17,12,288,289,290,291,292,293,294,295,296,297,298,299"

. $(dirname $(realpath $0))/shared/docker-run
