#!/bin/bash

WINEHQ="latest"
ROOT_DIR="/home/thomas/games/hmbm"
RUN="wine HitmanBloodMoney.exe"
WINETRICKS="vd=1920x1080 d3dx9"
SET_LAA="HitmanBloodMoney.exe"

. $(dirname $(realpath $0))/shared/docker-run
