#!/bin/bash

WINEHQ="stable-9.0.0.0-bookworm"
WINETRICKS="dxvk2030 vd=1920x1080"

ROOT_DIR="/home/thomas/games/hmbm"
RUN="wine HitmanBloodMoney.exe"
SET_LAA="HitmanBloodMoney.exe"

. $(dirname $(realpath $0))/shared/docker-run
