#!/bin/bash

WINEHQ="latest"
ROOT_DIR="/home/thomas/games/nfsu2"
RUN="wine SPEED2.EXE"
WINETRICKS="vd=1280x1024 dxvk"
WINEARCH="win32"
SET_LAA="SPEED2.EXE"

. $(dirname $(realpath $0))/shared/controller/triggers
. $(dirname $(realpath $0))/shared/docker-run
