#!/bin/bash

WINEHQ="latest"
ROOT_DIR="/home/thomas/games/soasersp"
RUN="wine64 soasersp.exe"
WINETRICKS="dxvk renderer=vulkan"
SET_LAA="soasersp.exe"
WINEARCH="win64"

. $(dirname $(realpath $0))/shared/docker-run
