#!/bin/bash

WINEHQ="8.0.1-stable-bookworm"
#WINETRICKS="dxvk"

ROOT_DIR="/home/thomas/games/stalker-anomaly"
#RUN="wine ./bin/AnomalyDX8.exe"
RUN="wine AnomalyLauncher.exe"

WINEARCH="win64"
. $(dirname $(realpath $0))/shared/docker-run
