#!/bin/bash

WINEHQ="latest"
ROOT_DIR="/home/thomas/games/swrs"
RUN="wine ./Rogue\ Squadron.EXE"
#WINETRICKS="win7 vd=1920x1080 dxvk"
APP_SUB_DIR="/ROGUE"

. $(dirname $(realpath $0))/shared/controller/triggers
. $(dirname $(realpath $0))/shared/docker-run
