#!/bin/bash

WINEHQ="latest"
ROOT_DIR="/home/thomas/games/ts2"
RUN="wine /home/wine/app/The\ Sims\ 2\ Mansion\ and\ Garden\ Stuff/TSBin/Sims2EP9.exe"
WINETRICKS="winxp vd=1920x1080 dxvk renderer=vulkan"
SET_LAA=""

. $(dirname $(realpath $0))/shared/docker-run
