#!/bin/bash

CACHE="$HOME/.cache/winehq-docker"

if [ ! -d "$ROOT_DIR" ] ; then
  echo "'$ROOT_DIR' ROOT_DIR not found!"
  exit 1
fi

mkdir -p "$CACHE"
mkdir -p "$ROOT_DIR/app"
mkdir -p "$ROOT_DIR/install"
mkdir -p "$ROOT_DIR/user"
mkdir -p "$ROOT_DIR/wineprefix"

CMD="wine $RUN_EXE"
if [ "$RUN_EXE" = "" ] ; then
  echo "No RUN_EXE, defaulting to bash"
  CMD="bash -l"
fi

docker run --rm -it \
  --name wine \
  --device /dev/dri \
  --device /dev/input \
  --hostname $( hostname ) \
  --ipc="host" \
  -e USER_ID=$(id -u) \
  -e VIDEO_GID=$( cat /etc/group | grep video | cut -f3 -d":" ) \
  -e INPUT_GID=$( cat /etc/group | grep input | cut -f3 -d":" ) \
  -e WINETRICKS="${WINETRICKS}" \
  -e SET_LAA="${SET_LAA}" \
  -e SDL_JOYSTICK_DEVICE="${SDL_JOYSTICK_DEVICE}" \
  -e SDL_GAMECONTROLLERCONFIG="$SDL_GAMECONTROLLERCONFIG"\
  -e HOME=/home/wine \
  -e DISPLAY=unix$DISPLAY \
  -v /tmp/.X11-unix:/tmp/.X11-unix \
  -v $HOME/.Xauthority:/home/wine/.Xauthority:ro \
  -e PULSE_SERVER=unix:/pulse \
  -v /run/user/$(id -u)/pulse/native:/pulse \
  -v $CACHE:/home/wine/.cache \
  -v $ROOT_DIR/app:/home/wine/app \
  -v $ROOT_DIR/install:/home/wine/install \
  -v $ROOT_DIR/user:/home/wine/user \
  -v $ROOT_DIR/wineprefix:/home/wine/.wine \
  -w /home/wine/app \
  -e WINEDLLOVERRIDES="$WINEDLLOVERRIDES" \
  0lfi/winehq:${WINEHQ:-latest} \
  bash -c "su wine -p -c \"$CMD\""
