#!/bin/bash

#SDL_GAMECONTROLLERCONFIG="03000000100800000300000000000000,PS2 Controller,a:b2,b:b1,back:b8,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,dpup:h0.1,leftshoulder:b6,leftstick:b10,lefttrigger:b4,leftx:a0,lefty:a1,rightshoulder:b7,rightstick:b11,righttrigger:b5,rightx:a4,righty:a2,start:b9,x:b3,y:b0,"

SDL_GAMECONTROLLERCONFIG="03000000100800000300000000000000,PS2 Controller,a:b2,b:b1,back:b8,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,dpup:h0.1,leftshoulder:b6,leftstick:b4,lefttrigger:b10,leftx:a0,lefty:a1,rightshoulder:b7,rightstick:b5,righttrigger:b11,rightx:a3,righty:a2,start:b9,x:b3,y:b0,"
